/**
 * Handlers for Reproduction
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reproductions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ReproductionsDomainModule } from "../dependencies/reproductions-ddd.dependencies.js";
import type { CreateReproductionInput, GetReproductionInput, ListReproductionsInput } from "@narriva/services/reproductions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/reproductions
 * Operation: listReproductions
 */
export async function listReproductions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], narrativeId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ReproductionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListReproductionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.reproductions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/reproductions
 * Operation: createReproduction
 */
export async function createReproduction(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ReproductionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateReproductionInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.reproductions.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/tenants/me/reproductions/{reproductionId}
 * Operation: getReproduction
 */
export async function getReproduction(
  request: FastifyRequest<{ Params: { reproductionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ReproductionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetReproductionInput = {
    reproductionId: request.params.reproductionId,
  };
  const result = await deps.useCases.reproductions.get.execute(input);
  return reply.code(200).send(result);
}


