/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@narriva/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildApprovalsDomainModule,
  buildDeliveriesDomainModule,
  buildIdentityDomainModule,
  buildNarrativesDomainModule,
  buildReproductionsDomainModule,
  buildSnapshotsDomainModule,
  buildTemplatesDomainModule,
} from "../domains/index.js";
import type {
  ApprovalsDomainModule,
  DeliveriesDomainModule,
  IdentityDomainModule,
  NarrativesDomainModule,
  ReproductionsDomainModule,
  SnapshotsDomainModule,
  TemplatesDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private approvalsModule: ApprovalsDomainModule | null = null;
  private deliveriesModule: DeliveriesDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private narrativesModule: NarrativesDomainModule | null = null;
  private reproductionsModule: ReproductionsDomainModule | null = null;
  private snapshotsModule: SnapshotsDomainModule | null = null;
  private templatesModule: TemplatesDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get approvals domain module
   */
  getApprovalsDependencies(): ApprovalsDomainModule {
    if (!this.approvalsModule) {
      this.approvalsModule = buildApprovalsDomainModule(this.dynamoClient);
    }
    return this.approvalsModule;
  }

  /**
   * Get deliveries domain module
   */
  getDeliveriesDependencies(): DeliveriesDomainModule {
    if (!this.deliveriesModule) {
      this.deliveriesModule = buildDeliveriesDomainModule(this.dynamoClient);
    }
    return this.deliveriesModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get narratives domain module
   */
  getNarrativesDependencies(): NarrativesDomainModule {
    if (!this.narrativesModule) {
      this.narrativesModule = buildNarrativesDomainModule(this.dynamoClient);
    }
    return this.narrativesModule;
  }

  /**
   * Get reproductions domain module
   */
  getReproductionsDependencies(): ReproductionsDomainModule {
    if (!this.reproductionsModule) {
      this.reproductionsModule = buildReproductionsDomainModule(this.dynamoClient);
    }
    return this.reproductionsModule;
  }

  /**
   * Get snapshots domain module
   */
  getSnapshotsDependencies(): SnapshotsDomainModule {
    if (!this.snapshotsModule) {
      this.snapshotsModule = buildSnapshotsDomainModule(this.dynamoClient);
    }
    return this.snapshotsModule;
  }

  /**
   * Get templates domain module
   */
  getTemplatesDependencies(): TemplatesDomainModule {
    if (!this.templatesModule) {
      this.templatesModule = buildTemplatesDomainModule(this.dynamoClient);
    }
    return this.templatesModule;
  }

  clearApprovalsDependencies(): void { this.approvalsModule = null; }
  clearDeliveriesDependencies(): void { this.deliveriesModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearNarrativesDependencies(): void { this.narrativesModule = null; }
  clearReproductionsDependencies(): void { this.reproductionsModule = null; }
  clearSnapshotsDependencies(): void { this.snapshotsModule = null; }
  clearTemplatesDependencies(): void { this.templatesModule = null; }

  getApprovalsDependenciesForRequest(): ApprovalsDomainModule {
    return this.getApprovalsDependencies();
  }

  getDeliveriesDependenciesForRequest(): DeliveriesDomainModule {
    return this.getDeliveriesDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getNarrativesDependenciesForRequest(): NarrativesDomainModule {
    return this.getNarrativesDependencies();
  }

  getReproductionsDependenciesForRequest(): ReproductionsDomainModule {
    return this.getReproductionsDependencies();
  }

  getSnapshotsDependenciesForRequest(): SnapshotsDomainModule {
    return this.getSnapshotsDependencies();
  }

  getTemplatesDependenciesForRequest(): TemplatesDomainModule {
    return this.getTemplatesDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.approvalsModule = null;
    this.deliveriesModule = null;
    this.identityModule = null;
    this.narrativesModule = null;
    this.reproductionsModule = null;
    this.snapshotsModule = null;
    this.templatesModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
