/**
 * GetDelivery handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deliveries
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDelivery } from "@narriva/api-server/domains/deliveries/handlers";
import type { DeliveriesDDDDependencies } from "@narriva/api-server/domains/deliveries";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@narriva/tests/shared";
import { DELIVERIES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDelivery", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DeliveriesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DeliveriesDDDDependencies>(
      DELIVERIES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDelivery, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { deliveryId: entity.id };

    await getDelivery(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDelivery.execute).toHaveBeenCalledWith(expect.objectContaining({ deliveryId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { deliveryId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDelivery, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDelivery(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
