/**
 * Handlers for Cancel
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deliveries
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DeliveriesDomainModule } from "../dependencies/deliveries-ddd.dependencies.js";
import type { CancelDeliveryInput } from "@narriva/services/deliveries";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v0/tenants/me/deliveries/{deliveryId}/cancel
 * Operation: cancelDelivery
 */
export async function cancelDelivery(
  request: FastifyRequest<{ Params: { deliveryId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DeliveriesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CancelDeliveryInput = {
    deliveryId: request.params.deliveryId,
  };
  const result = await deps.useCases.cancels.update.execute(input);
  return reply.code(200).send(result);
}


