/**
 * Handlers for Delivery
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deliveries
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DeliveriesDomainModule } from "../dependencies/deliveries-ddd.dependencies.js";
import type { CreateDeliveryInput, GetDeliveryInput, ListDeliveriesInput } from "@narriva/services/deliveries";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/deliveries
 * Operation: listDeliveries
 */
export async function listDeliveries(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[], channel?: string | string[], narrativeId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DeliveriesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDeliveriesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.deliveries.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/deliveries
 * Operation: createDelivery
 */
export async function createDelivery(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DeliveriesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateDeliveryInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.deliveries.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/tenants/me/deliveries/{deliveryId}
 * Operation: getDelivery
 */
export async function getDelivery(
  request: FastifyRequest<{ Params: { deliveryId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DeliveriesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDeliveryInput = {
    deliveryId: request.params.deliveryId,
  };
  const result = await deps.useCases.deliveries.get.execute(input);
  return reply.code(200).send(result);
}


