/**
 * Approvals DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: approvals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Approvals Domain Module - Composition root
 *
 * DDD: Composition root for approvals domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ApprovalRepositoryAdapter,
} from "@narriva/adapters/approvals";
import { getIdGeneratorService } from "@narriva/adapters";
import type { AdapterDynamoDBClient } from "@narriva/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateNarrativeApproval,
  ExecuteGetApproval,
  ExecuteListApprovals,
} from "@narriva/services/approvals/usecases";
// Ports (interfaces)
import type {
  ApprovalRepository,
} from "@narriva/services/approvals/ports";

export interface ApprovalsDomainModule {
  repos: {
    approvals: ApprovalRepository;
  };
  useCases: {
    approvals: {
      create: ExecuteCreateNarrativeApproval;
      get: ExecuteGetApproval;
      list: ExecuteListApprovals;
    };
  };
}

export function buildApprovalsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ApprovalsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      approvals?: ApprovalRepository;
    } = {};

    obj.approvals = new ApprovalRepositoryAdapter(dynamoClient);
    return {
      approvals: obj.approvals!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    approvals: {
      create: new ExecuteCreateNarrativeApproval(executionContext, idGenerator, repos.approvals),
      get: new ExecuteGetApproval(executionContext, idGenerator, repos.approvals),
      list: new ExecuteListApprovals(executionContext, idGenerator, repos.approvals),
    },
  };
  return { repos, useCases: useCases as ApprovalsDomainModule["useCases"] };
}
