/**
 * ExecuteCreateNarrativeApproval - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: approvals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateNarrativeApproval Use Case
 *
 * DDD: Application use case for create Approval.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateNarrativeApprovalInput, CreateNarrativeApprovalOutput } from "../dto/approval.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { ApprovalRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateNarrativeApproval {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly approval: ApprovalRepository
  ) {}

  async execute(input: CreateNarrativeApprovalInput): Promise<CreateNarrativeApprovalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.aprId();

    // All field names extracted from OpenAPI spec: comment, outcome
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.outcome) {
      throw new ValidationError("outcome is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (approvals domain)
    const entityId = this.idGenerator.aprId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.approval.createNarrativeApproval({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateNarrativeApprovalOutput;
  }
}
