/**
 * ExecuteGetApproval - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: approvals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetApproval Use Case
 *
 * DDD: Application use case for get Approval.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetApprovalInput, GetApprovalOutput } from "../dto/approval.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { ApprovalRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetApproval {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly approval: ApprovalRepository
  ) {}

  async execute(input: GetApprovalInput): Promise<GetApprovalOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.aprId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).approvalId) {
      throw new ValidationError("approvalId is required");
    }
    const approvalId = (input as any).approvalId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.approval.getApproval({ approvalId: approvalId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${approvalId}`);
    }

    return entity as GetApprovalOutput;
  }
}
