/**
 * GetTemplate handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getTemplate } from "@narriva/api-server/domains/templates/handlers";
import type { TemplatesDDDDependencies } from "@narriva/api-server/domains/templates";
import { createTemplate as createTemplateEntity } from "@narriva/factories/templates";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@narriva/tests/shared";
import { TEMPLATES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetTemplate", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TemplatesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TemplatesDDDDependencies>(
      TEMPLATES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createTemplateEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetTemplate, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { templateId: entity.id };

    await getTemplate(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetTemplate.execute).toHaveBeenCalledWith(expect.objectContaining({ templateId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { templateId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetTemplate, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getTemplate(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
