/**
 * ListTemplates handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listTemplates } from "@narriva/api-server/domains/templates/handlers";
import type { TemplatesDDDDependencies } from "@narriva/api-server/domains/templates";
import { createTemplate as createTemplateEntity } from "@narriva/factories/templates";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@narriva/tests/shared";
import { TEMPLATES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListTemplates", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TemplatesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TemplatesDDDDependencies>(
      TEMPLATES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createTemplateEntity({ orgId }),
      createTemplateEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListTemplates, "execute").mockResolvedValue(useCaseResult);

    await listTemplates(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListTemplates.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
