/**
 * JudgmentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * JudgmentRepository Port
 *
 * DDD: Application port for judgmentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AddNarrativeJudgmentOverlayInput, AddNarrativeJudgmentOverlayOutput } from "../dto/judgment.dto";
export interface JudgmentRepository {
  addNarrativeJudgmentOverlay(input: AddNarrativeJudgmentOverlayInput): Promise<AddNarrativeJudgmentOverlayOutput>;
}

export type { AddNarrativeJudgmentOverlayInput, AddNarrativeJudgmentOverlayOutput } from "../dto/judgment.dto";
