/**
 * NarrativeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * NarrativeRepository Port
 *
 * DDD: Application port for narrativerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GenerateNarrativeInput, GenerateNarrativeOutput, GetNarrativeInput, GetNarrativeOutput, ListNarrativesInput, ListNarrativesOutput } from "../dto/narrative.dto";
export interface NarrativeRepository {
  listNarratives(input: ListNarrativesInput): Promise<ListNarrativesOutput>;
  generateNarrative(input: GenerateNarrativeInput): Promise<GenerateNarrativeOutput>;
  getNarrative(input: GetNarrativeInput): Promise<GetNarrativeOutput>;
}

export type { GenerateNarrativeInput, GenerateNarrativeOutput, GetNarrativeInput, GetNarrativeOutput, ListNarrativesInput, ListNarrativesOutput } from "../dto/narrative.dto";
