/**
 * ProductivityRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProductivityRepository Port
 *
 * DDD: Application port for productivityrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetNarrativeProductivitySummaryInput, GetNarrativeProductivitySummaryOutput } from "../dto/productivity.dto";
export interface ProductivityRepository {
  getNarrativeProductivitySummary(input: GetNarrativeProductivitySummaryInput): Promise<GetNarrativeProductivitySummaryOutput>;
}

export type { GetNarrativeProductivitySummaryInput, GetNarrativeProductivitySummaryOutput } from "../dto/productivity.dto";
