/**
 * ReproductionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reproductions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReproductionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReproductionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReproductionRepository,
} from "@narriva/services/reproductions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReproductionRepositoryDdb } from "./reproduction-repository.ddb.js";

/**
 * ReproductionRepositoryAdapter
 *
 * Implements ReproductionRepository port for infrastructure layer.
 */
export class ReproductionRepositoryAdapter implements ReproductionRepository {
  private readonly ddb: ReproductionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReproductionRepositoryDdb(this.dynamoClient);
  }

  async listReproductions(input: Parameters<ReproductionRepository['listReproductions']>[0]): Promise<Awaited<ReturnType<ReproductionRepository['listReproductions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listReproductions(input);
  }

  async createReproduction(input: Parameters<ReproductionRepository['createReproduction']>[0]): Promise<Awaited<ReturnType<ReproductionRepository['createReproduction']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createReproduction(input);
  }

  async getReproduction(input: Parameters<ReproductionRepository['getReproduction']>[0]): Promise<Awaited<ReturnType<ReproductionRepository['getReproduction']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getReproduction(input);
  }
}
