/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the templates domain.
 * Use these factories in tests to create test data.
 */

export { createCreateApproveRequest } from "./approve/dto/create-approve.dto.factory.js";
export { createCreateRetireRequest } from "./retire/dto/create-retire.dto.factory.js";
export { createCreateSubmitRequest } from "./submit/dto/create-submit.dto.factory.js";
export { createDisclosureRule } from "./disclosure-rule/entity/disclosure-rule.entity.factory.js";
export { createTemplate } from "./template/entity/template.entity.factory.js";
