/**
 * ExecuteCreateReproduction - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reproductions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateReproduction Use Case
 *
 * DDD: Application use case for create Reproduction.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateReproductionInput, CreateReproductionOutput } from "../dto/reproduction.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { ReproductionRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateReproduction {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly reproduction: ReproductionRepository
  ) {}

  async execute(input: CreateReproductionInput): Promise<CreateReproductionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rprId();

    // All field names extracted from OpenAPI spec: narrativeId, snapshotId, templateId, templateVersion
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.narrativeId) {
      throw new ValidationError("narrativeId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (reproductions domain)
    const entityId = this.idGenerator.rprId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.reproduction.createReproduction({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateReproductionOutput;
  }
}
