/**
 * ExecuteListReproductions - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reproductions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListReproductions Use Case
 *
 * DDD: Application use case for list Reproduction.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListReproductionsInput, ListReproductionsOutput } from "../dto/reproduction.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { ReproductionRepository } from "../ports";

export class ExecuteListReproductions {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly reproduction: ReproductionRepository
  ) {}

  async execute(input: ListReproductionsInput): Promise<ListReproductionsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rprId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.reproduction.listReproductions({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListReproductionsOutput;
  }
}
