/**
 * ExecuteGetReproduction - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reproductions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetReproduction Use Case
 *
 * DDD: Application use case for get Reproduction.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetReproductionInput, GetReproductionOutput } from "../dto/reproduction.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { ReproductionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetReproduction {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly reproduction: ReproductionRepository
  ) {}

  async execute(input: GetReproductionInput): Promise<GetReproductionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rprId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).reproductionId) {
      throw new ValidationError("reproductionId is required");
    }
    const reproductionId = (input as any).reproductionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.reproduction.getReproduction({ reproductionId: reproductionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${reproductionId}`);
    }

    return entity as GetReproductionOutput;
  }
}
