/**
 * ReproductionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reproductions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReproductionRepository Port
 *
 * DDD: Application port for reproductionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateReproductionInput, CreateReproductionOutput, GetReproductionInput, GetReproductionOutput, ListReproductionsInput, ListReproductionsOutput } from "../dto/reproduction.dto";
export interface ReproductionRepository {
  listReproductions(input: ListReproductionsInput): Promise<ListReproductionsOutput>;
  createReproduction(input: CreateReproductionInput): Promise<CreateReproductionOutput>;
  getReproduction(input: GetReproductionInput): Promise<GetReproductionOutput>;
}

export type { CreateReproductionInput, CreateReproductionOutput, GetReproductionInput, GetReproductionOutput, ListReproductionsInput, ListReproductionsOutput } from "../dto/reproduction.dto";
