/**
 * ExecuteCancelDelivery - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deliveries
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCancelDelivery Use Case
 *
 * DDD: Application use case for update Cancel.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CancelDeliveryInput, CancelDeliveryOutput } from "../dto/cancel.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { CancelRepository } from "../ports";
import { NotFoundError, PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteCancelDelivery {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly cancel: CancelRepository
  ) {}

  async execute(input: CancelDeliveryInput): Promise<CancelDeliveryOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dlvId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).deliveryId) {
      throw new ValidationError("deliveryId is required");
    }
    const deliveryId = (input as any).deliveryId;

    // Load existing entity
    const existing = await this.cancel.getDelivery({ deliveryId: deliveryId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!existing) {
      throw new NotFoundError(`Entity not found: ${deliveryId}`);
    }
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.cancel.cancelDelivery({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as CancelDeliveryOutput;
  }
}
