/**
 * ExecuteCreateDelivery - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deliveries
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateDelivery Use Case
 *
 * DDD: Application use case for create Delivery.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateDeliveryInput, CreateDeliveryOutput } from "../dto/delivery.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { DeliveryRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateDelivery {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly delivery: DeliveryRepository
  ) {}

  async execute(input: CreateDeliveryInput): Promise<CreateDeliveryOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dlvId();

    // All field names extracted from OpenAPI spec: channel, narrativeId, recipientRef, scheduledAt
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.channel) {
      throw new ValidationError("channel is required");
    }
    if (!input.narrativeId) {
      throw new ValidationError("narrativeId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (deliveries domain)
    const entityId = this.idGenerator.dlvId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.delivery.createDelivery({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateDeliveryOutput;
  }
}
