/**
 * GetReproduction DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reproductions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetReproductionParams } from "@narriva/core/reproductions";

export function createGetReproductionRequest(overrides: Partial<GetReproductionParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
