/**
 * Handlers for Judgment
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { NarrativesDomainModule } from "../dependencies/narratives-ddd.dependencies.js";
import type { AddNarrativeJudgmentOverlayInput } from "@narriva/services/narratives";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v0/tenants/me/narratives/{narrativeId}/judgment
 * Operation: addNarrativeJudgmentOverlay
 */
export async function addNarrativeJudgmentOverlay(
  request: FastifyRequest<{ Params: { narrativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: NarrativesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AddNarrativeJudgmentOverlayInput = {
    narrativeId: request.params.narrativeId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.judgments.create.execute(input);
  return reply.code(200).send(result);
}


