/**
 * Handlers for Productivity
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { NarrativesDomainModule } from "../dependencies/narratives-ddd.dependencies.js";
import type { GetNarrativeProductivitySummaryInput } from "@narriva/services/narratives";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/narratives/productivity
 * Operation: getNarrativeProductivitySummary
 */
export async function getNarrativeProductivitySummary(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { periodKey?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: NarrativesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetNarrativeProductivitySummaryInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.productivities.get.execute(input);
  return reply.code(200).send(result);
}


