/**
 * Authoritative DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: snapshots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Authoritative DTOs
 *
 * DDD: Application DTOs for Authoritative use cases.
 */

import type { MarkFactFieldAuthoritativeParams, MarkFactFieldAuthoritativeRequestInput } from "@narriva/core/snapshots/types";

export type MarkFactFieldAuthoritativeInput = MarkFactFieldAuthoritativeParams & MarkFactFieldAuthoritativeRequestInput;

export type MarkFactFieldAuthoritativeOutput = {};
