/**
 * Lock DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: snapshots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Lock DTOs
 *
 * DDD: Application DTOs for Lock use cases.
 */

import type { LockFactSnapshotParams } from "@narriva/core/snapshots/types";

export type LockFactSnapshotInput = LockFactSnapshotParams;

export type LockFactSnapshotOutput = {};
