/**
 * Snapshot DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: snapshots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Snapshot DTOs
 *
 * DDD: Application DTOs for Snapshot use cases.
 */

import type { CreateFactSnapshotRequestInput, GetFactSnapshotParams, ListFactSnapshotsParams } from "@narriva/core/snapshots/types";

export type ListFactSnapshotsInput = ListFactSnapshotsParams;

export type CreateFactSnapshotInput = CreateFactSnapshotRequestInput;

export type GetFactSnapshotInput = GetFactSnapshotParams;

export type ListFactSnapshotsOutput = {};

export type CreateFactSnapshotOutput = {};

export type GetFactSnapshotOutput = {};
