/**
 * JudgmentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * JudgmentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements JudgmentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  JudgmentRepository,
} from "@narriva/services/narratives";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { JudgmentRepositoryDdb } from "./judgment-repository.ddb.js";

/**
 * JudgmentRepositoryAdapter
 *
 * Implements JudgmentRepository port for infrastructure layer.
 */
export class JudgmentRepositoryAdapter implements JudgmentRepository {
  private readonly ddb: JudgmentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new JudgmentRepositoryDdb(this.dynamoClient);
  }

  async addNarrativeJudgmentOverlay(input: Parameters<JudgmentRepository['addNarrativeJudgmentOverlay']>[0]): Promise<Awaited<ReturnType<JudgmentRepository['addNarrativeJudgmentOverlay']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.addNarrativeJudgmentOverlay(input);
  }
}
