/**
 * NarrativeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * NarrativeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements NarrativeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  NarrativeRepository,
} from "@narriva/services/narratives";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { NarrativeRepositoryDdb } from "./narrative-repository.ddb.js";

/**
 * NarrativeRepositoryAdapter
 *
 * Implements NarrativeRepository port for infrastructure layer.
 */
export class NarrativeRepositoryAdapter implements NarrativeRepository {
  private readonly ddb: NarrativeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new NarrativeRepositoryDdb(this.dynamoClient);
  }

  async listNarratives(input: Parameters<NarrativeRepository['listNarratives']>[0]): Promise<Awaited<ReturnType<NarrativeRepository['listNarratives']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listNarratives(input);
  }

  async generateNarrative(input: Parameters<NarrativeRepository['generateNarrative']>[0]): Promise<Awaited<ReturnType<NarrativeRepository['generateNarrative']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.generateNarrative(input);
  }

  async getNarrative(input: Parameters<NarrativeRepository['getNarrative']>[0]): Promise<Awaited<ReturnType<NarrativeRepository['getNarrative']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getNarrative(input);
  }
}
