/**
 * ProductivityRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProductivityRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ProductivityRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ProductivityRepository,
} from "@narriva/services/narratives";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ProductivityRepositoryDdb } from "./productivity-repository.ddb.js";

/**
 * ProductivityRepositoryAdapter
 *
 * Implements ProductivityRepository port for infrastructure layer.
 */
export class ProductivityRepositoryAdapter implements ProductivityRepository {
  private readonly ddb: ProductivityRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ProductivityRepositoryDdb(this.dynamoClient);
  }

  async getNarrativeProductivitySummary(input: Parameters<ProductivityRepository['getNarrativeProductivitySummary']>[0]): Promise<Awaited<ReturnType<ProductivityRepository['getNarrativeProductivitySummary']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getNarrativeProductivitySummary(input);
  }
}
