/**
 * ExecuteListTemplates - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListTemplates Use Case
 *
 * DDD: Application use case for list Template.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListTemplatesInput, ListTemplatesOutput } from "../dto/template.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { TemplateRepository } from "../ports";

export class ExecuteListTemplates {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly template: TemplateRepository
  ) {}

  async execute(input: ListTemplatesInput): Promise<ListTemplatesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.tplId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.template.listTemplates({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListTemplatesOutput;
  }
}
