/**
 * ExecuteCreateDisclosureRule - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateDisclosureRule Use Case
 *
 * DDD: Application use case for create DisclosureRule.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateDisclosureRuleInput, CreateDisclosureRuleOutput } from "../dto/disclosure-rule.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { DisclosureRuleRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateDisclosureRule {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly disclosureRule: DisclosureRuleRepository
  ) {}

  async execute(input: CreateDisclosureRuleInput): Promise<CreateDisclosureRuleOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.tplId();

    // All field names extracted from OpenAPI spec: bannedClaimPatterns, body, name
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.body) {
      throw new ValidationError("body is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (templates domain)
    const entityId = this.idGenerator.tplId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.disclosureRule.createDisclosureRule({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateDisclosureRuleOutput;
  }
}
