/**
 * Handlers for Approval
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: approvals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ApprovalsDomainModule } from "../dependencies/approvals-ddd.dependencies.js";
import type { CreateNarrativeApprovalInput, GetApprovalInput, ListApprovalsInput } from "@narriva/services/approvals";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/approvals
 * Operation: listApprovals
 */
export async function listApprovals(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], riskTier?: string | string[], outcome?: string | string[], narrativeId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ApprovalsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListApprovalsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.approvals.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/narratives/{narrativeId}/approvals
 * Operation: createNarrativeApproval
 */
export async function createNarrativeApproval(
  request: FastifyRequest<{ Params: { narrativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ApprovalsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateNarrativeApprovalInput = {
    narrativeId: request.params.narrativeId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.approvals.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/tenants/me/approvals/{approvalId}
 * Operation: getApproval
 */
export async function getApproval(
  request: FastifyRequest<{ Params: { approvalId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ApprovalsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetApprovalInput = {
    approvalId: request.params.approvalId,
  };
  const result = await deps.useCases.approvals.get.execute(input);
  return reply.code(200).send(result);
}


