/**
 * AddNarrativeJudgmentOverlay handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { addNarrativeJudgmentOverlay } from "@narriva/api-server/domains/narratives/handlers";
import type { NarrativesDDDDependencies } from "@narriva/api-server/domains/narratives";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@narriva/tests/shared";
import { NARRATIVES_USE_CASES } from "../__factories__/use-cases.js";

describe("AddNarrativeJudgmentOverlay", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: NarrativesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<NarrativesDDDDependencies>(
      NARRATIVES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeAddNarrativeJudgmentOverlay, "execute").mockResolvedValue(useCaseResult);

    await addNarrativeJudgmentOverlay(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeAddNarrativeJudgmentOverlay.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
