/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as approvalsRoutes from "../../domains/approvals/routes/index.js";
import * as deliveriesRoutes from "../../domains/deliveries/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as narrativesRoutes from "../../domains/narratives/routes/index.js";
import * as reproductionsRoutes from "../../domains/reproductions/routes/index.js";
import * as snapshotsRoutes from "../../domains/snapshots/routes/index.js";
import * as templatesRoutes from "../../domains/templates/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "approvals", mod: approvalsRoutes },
  { domain: "deliveries", mod: deliveriesRoutes },
  {
    domain: "identity",
    mod: identityRoutes,
    // Keep auth login/me/logout/refresh registered (API-key + password sessions).
    exclude: [
      "authRoutes",
      "signupRoutes",
      "sessionRoutes",
      "tokenRoutes",
      "profileRoutes",
    ],
  },
  { domain: "narratives", mod: narrativesRoutes },
  { domain: "reproductions", mod: reproductionsRoutes },
  { domain: "snapshots", mod: snapshotsRoutes },
  { domain: "templates", mod: templatesRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
