/**
 * Template Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { TemplateEntity } from "@narriva/core/templates/models/index.js";
import { templatesSchemas } from "@narriva/core/templates";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "tpl";

export function createTemplate(overrides: Partial<TemplateEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    audience: overrides.audience ?? "retail_client",
    body: overrides.body ?? faker.lorem.paragraph(),
    locale: overrides.locale ?? faker.lorem.word(),
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "draft",
    templateId: overrides.templateId ?? `tpl_${ulid().toLowerCase()}`,
    version: overrides.version ?? faker.number.int(),
    ...overrides,
  };

  return templatesSchemas.Template.parse(raw);
}

export function templateBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createTemplate(overrides));
}
