/**
 * ListApproval DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: approvals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListApprovalsParams } from "@narriva/core/approvals";

export function createListApprovalRequest(overrides: Partial<ListApprovalsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
