/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: reproductions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @narriva/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@narriva/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@narriva/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@narriva/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@narriva/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@narriva/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _approvals from "./approvals/index.js";
import * as _deliveries from "./deliveries/index.js";
import * as _identity from "./identity/index.js";
import * as _narratives from "./narratives/index.js";
import * as _reproductions from "./reproductions/index.js";
import * as _snapshots from "./snapshots/index.js";
import * as _templates from "./templates/index.js";

// Export as namespaces
export const _shared = __shared;
export const approvals = _approvals;
export const deliveries = _deliveries;
export const identity = _identity;
export const narratives = _narratives;
export const reproductions = _reproductions;
export const snapshots = _snapshots;
export const templates = _templates;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@narriva/core"; activity.types.*
//   - Direct exports: import * from "@narriva/core/activity/types/index.js"
//   - Direct exports: import * from "@narriva/core/activity/repositories/index.js"
//   - Direct exports: import * from "@narriva/core/activity/models/index.js"
//   - Direct exports: import * from "@narriva/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Approvals Service
export { schemas as ApprovalsSchemas } from "./approvals/schemas/approvals.schemas.js";

// Deliveries Service
export { schemas as DeliveriesSchemas } from "./deliveries/schemas/deliveries.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Narratives Service
export { schemas as NarrativesSchemas } from "./narratives/schemas/narratives.schemas.js";

// Reproductions Service
export { schemas as ReproductionsSchemas } from "./reproductions/schemas/reproductions.schemas.js";

// Snapshots Service
export { schemas as SnapshotsSchemas } from "./snapshots/schemas/snapshots.schemas.js";

// Templates Service
export { schemas as TemplatesSchemas } from "./templates/schemas/templates.schemas.js";

