/**
 * Narrative DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Narrative DTOs
 *
 * DDD: Application DTOs for Narrative use cases.
 */

import type { GenerateNarrativeRequestInput, GetNarrativeParams, ListNarrativesParams } from "@narriva/core/narratives/types";

export type ListNarrativesInput = ListNarrativesParams;

export type GenerateNarrativeInput = GenerateNarrativeRequestInput;

export type GetNarrativeInput = GetNarrativeParams;

export type ListNarrativesOutput = {};

export type GenerateNarrativeOutput = {};

export type GetNarrativeOutput = {};
