/**
 * Productivity DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Productivity DTOs
 *
 * DDD: Application DTOs for Productivity use cases.
 */

import type { GetNarrativeProductivitySummaryParams } from "@narriva/core/narratives/types";

export type GetNarrativeProductivitySummaryInput = GetNarrativeProductivitySummaryParams;

export type GetNarrativeProductivitySummaryOutput = {};
