/**
 * Approval Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: approvals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ApprovalEntity } from "@narriva/core/approvals/models/index.js";
import { approvalsSchemas } from "@narriva/core/approvals";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "apr";

export function createApproval(overrides: Partial<ApprovalEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    approvalId: overrides.approvalId ?? `apr_${ulid().toLowerCase()}`,
    narrativeId: overrides.narrativeId ?? faker.string.uuid(),
    outcome: overrides.outcome ?? "approved",
    riskTier: overrides.riskTier ?? "routine",
    ...overrides,
  };

  return approvalsSchemas.Approval.parse(raw);
}

export function approvalBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createApproval(overrides));
}
