/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v0/tenants/me/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List templates */
        get: operations["listTemplates"];
        put?: never;
        /** Create draft template */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/tenants/me/templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get template (includes logic outline / bindings) */
        get: operations["getTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/tenants/me/templates/{templateId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit draft template for compliance approval */
        post: operations["submitTemplateForApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/tenants/me/templates/{templateId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve template version */
        post: operations["approveTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/tenants/me/templates/{templateId}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire template (force migration off obsolete disclosures) */
        post: operations["retireTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v0/tenants/me/disclosure-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List disclosure rules */
        get: operations["listDisclosureRules"];
        put?: never;
        /** Create disclosure rule */
        post: operations["createDisclosureRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Audience: "retail_client" | "advisor" | "institutional";
        /** @enum {string} */
        TemplateStatus: "draft" | "approved" | "retired";
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        TemplateId: string;
        DisclosureRuleId: string;
        Template: {
            templateId: string;
            name: string;
            /** @enum {string} */
            audience: "retail_client" | "advisor" | "institutional";
            /** @example en-US */
            locale: string;
            version: number;
            /** @enum {string} */
            status: "draft" | "approved" | "retired";
            /** @description Template logic / body with fact slots. */
            body: string;
            /**
             * @default routine
             * @enum {string}
             */
            productRiskTier: "routine" | "elevated" | "high";
            disclosureRuleIds?: string[];
            bannedClaims?: string[];
            /** @description Human-readable template logic for audit (BR-11). */
            logicOutline?: string;
            boundFactKeys?: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            approvedAt?: string;
            /** Format: date-time */
            retiredAt?: string;
        };
        TemplateListData: {
            items: {
                templateId: string;
                name: string;
                /** @enum {string} */
                audience: "retail_client" | "advisor" | "institutional";
                /** @example en-US */
                locale: string;
                version: number;
                /** @enum {string} */
                status: "draft" | "approved" | "retired";
                /** @description Template logic / body with fact slots. */
                body: string;
                /**
                 * @default routine
                 * @enum {string}
                 */
                productRiskTier: "routine" | "elevated" | "high";
                disclosureRuleIds?: string[];
                bannedClaims?: string[];
                /** @description Human-readable template logic for audit (BR-11). */
                logicOutline?: string;
                boundFactKeys?: string[];
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                /** Format: date-time */
                approvedAt?: string;
                /** Format: date-time */
                retiredAt?: string;
            }[];
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        TemplateListResponse: {
            data: {
                items: {
                    templateId: string;
                    name: string;
                    /** @enum {string} */
                    audience: "retail_client" | "advisor" | "institutional";
                    /** @example en-US */
                    locale: string;
                    version: number;
                    /** @enum {string} */
                    status: "draft" | "approved" | "retired";
                    /** @description Template logic / body with fact slots. */
                    body: string;
                    /**
                     * @default routine
                     * @enum {string}
                     */
                    productRiskTier: "routine" | "elevated" | "high";
                    disclosureRuleIds?: string[];
                    bannedClaims?: string[];
                    /** @description Human-readable template logic for audit (BR-11). */
                    logicOutline?: string;
                    boundFactKeys?: string[];
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                    /** Format: date-time */
                    approvedAt?: string;
                    /** Format: date-time */
                    retiredAt?: string;
                }[];
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        TemplateCreateRequest: {
            name: string;
            /** @enum {string} */
            audience: "retail_client" | "advisor" | "institutional";
            locale: string;
            body: string;
            /** @enum {string} */
            productRiskTier?: "routine" | "elevated" | "high";
            disclosureRuleIds?: string[];
            bannedClaims?: string[];
            logicOutline?: string;
            boundFactKeys?: string[];
        };
        TemplateResponse: {
            data: {
                templateId: string;
                name: string;
                /** @enum {string} */
                audience: "retail_client" | "advisor" | "institutional";
                /** @example en-US */
                locale: string;
                version: number;
                /** @enum {string} */
                status: "draft" | "approved" | "retired";
                /** @description Template logic / body with fact slots. */
                body: string;
                /**
                 * @default routine
                 * @enum {string}
                 */
                productRiskTier: "routine" | "elevated" | "high";
                disclosureRuleIds?: string[];
                bannedClaims?: string[];
                /** @description Human-readable template logic for audit (BR-11). */
                logicOutline?: string;
                boundFactKeys?: string[];
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                /** Format: date-time */
                approvedAt?: string;
                /** Format: date-time */
                retiredAt?: string;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        DisclosureRule: {
            disclosureRuleId: string;
            name: string;
            body: string;
            bannedClaimPatterns?: string[];
            /** @enum {string} */
            status: "draft" | "approved" | "retired";
        };
        DisclosureRuleListData: {
            items: {
                disclosureRuleId: string;
                name: string;
                body: string;
                bannedClaimPatterns?: string[];
                /** @enum {string} */
                status: "draft" | "approved" | "retired";
            }[];
        };
        DisclosureRuleListResponse: {
            data: {
                items: {
                    disclosureRuleId: string;
                    name: string;
                    body: string;
                    bannedClaimPatterns?: string[];
                    /** @enum {string} */
                    status: "draft" | "approved" | "retired";
                }[];
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        DisclosureRuleCreateRequest: {
            name: string;
            body: string;
            bannedClaimPatterns?: string[];
        };
        DisclosureRuleResponse: {
            data: {
                disclosureRuleId: string;
                name: string;
                body: string;
                bannedClaimPatterns?: string[];
                /** @enum {string} */
                status: "draft" | "approved" | "retired";
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTemplates: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                audience?: "retail_client" | "advisor" | "institutional";
                status?: "draft" | "approved" | "retired";
                locale?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                templateId: string;
                                name: string;
                                /** @enum {string} */
                                audience: "retail_client" | "advisor" | "institutional";
                                /** @example en-US */
                                locale: string;
                                version: number;
                                /** @enum {string} */
                                status: "draft" | "approved" | "retired";
                                /** @description Template logic / body with fact slots. */
                                body: string;
                                /**
                                 * @default routine
                                 * @enum {string}
                                 */
                                productRiskTier: "routine" | "elevated" | "high";
                                disclosureRuleIds?: string[];
                                bannedClaims?: string[];
                                /** @description Human-readable template logic for audit (BR-11). */
                                logicOutline?: string;
                                boundFactKeys?: string[];
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                /** Format: date-time */
                                approvedAt?: string;
                                /** Format: date-time */
                                retiredAt?: string;
                            }[];
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    audience: "retail_client" | "advisor" | "institutional";
                    locale: string;
                    body: string;
                    /** @enum {string} */
                    productRiskTier?: "routine" | "elevated" | "high";
                    disclosureRuleIds?: string[];
                    bannedClaims?: string[];
                    logicOutline?: string;
                    boundFactKeys?: string[];
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            templateId: string;
                            name: string;
                            /** @enum {string} */
                            audience: "retail_client" | "advisor" | "institutional";
                            /** @example en-US */
                            locale: string;
                            version: number;
                            /** @enum {string} */
                            status: "draft" | "approved" | "retired";
                            /** @description Template logic / body with fact slots. */
                            body: string;
                            /**
                             * @default routine
                             * @enum {string}
                             */
                            productRiskTier: "routine" | "elevated" | "high";
                            disclosureRuleIds?: string[];
                            bannedClaims?: string[];
                            /** @description Human-readable template logic for audit (BR-11). */
                            logicOutline?: string;
                            boundFactKeys?: string[];
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            approvedAt?: string;
                            /** Format: date-time */
                            retiredAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            templateId: string;
                            name: string;
                            /** @enum {string} */
                            audience: "retail_client" | "advisor" | "institutional";
                            /** @example en-US */
                            locale: string;
                            version: number;
                            /** @enum {string} */
                            status: "draft" | "approved" | "retired";
                            /** @description Template logic / body with fact slots. */
                            body: string;
                            /**
                             * @default routine
                             * @enum {string}
                             */
                            productRiskTier: "routine" | "elevated" | "high";
                            disclosureRuleIds?: string[];
                            bannedClaims?: string[];
                            /** @description Human-readable template logic for audit (BR-11). */
                            logicOutline?: string;
                            boundFactKeys?: string[];
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            approvedAt?: string;
                            /** Format: date-time */
                            retiredAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    submitTemplateForApproval: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            templateId: string;
                            name: string;
                            /** @enum {string} */
                            audience: "retail_client" | "advisor" | "institutional";
                            /** @example en-US */
                            locale: string;
                            version: number;
                            /** @enum {string} */
                            status: "draft" | "approved" | "retired";
                            /** @description Template logic / body with fact slots. */
                            body: string;
                            /**
                             * @default routine
                             * @enum {string}
                             */
                            productRiskTier: "routine" | "elevated" | "high";
                            disclosureRuleIds?: string[];
                            bannedClaims?: string[];
                            /** @description Human-readable template logic for audit (BR-11). */
                            logicOutline?: string;
                            boundFactKeys?: string[];
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            approvedAt?: string;
                            /** Format: date-time */
                            retiredAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    approveTemplate: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            templateId: string;
                            name: string;
                            /** @enum {string} */
                            audience: "retail_client" | "advisor" | "institutional";
                            /** @example en-US */
                            locale: string;
                            version: number;
                            /** @enum {string} */
                            status: "draft" | "approved" | "retired";
                            /** @description Template logic / body with fact slots. */
                            body: string;
                            /**
                             * @default routine
                             * @enum {string}
                             */
                            productRiskTier: "routine" | "elevated" | "high";
                            disclosureRuleIds?: string[];
                            bannedClaims?: string[];
                            /** @description Human-readable template logic for audit (BR-11). */
                            logicOutline?: string;
                            boundFactKeys?: string[];
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            approvedAt?: string;
                            /** Format: date-time */
                            retiredAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    retireTemplate: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retired */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            templateId: string;
                            name: string;
                            /** @enum {string} */
                            audience: "retail_client" | "advisor" | "institutional";
                            /** @example en-US */
                            locale: string;
                            version: number;
                            /** @enum {string} */
                            status: "draft" | "approved" | "retired";
                            /** @description Template logic / body with fact slots. */
                            body: string;
                            /**
                             * @default routine
                             * @enum {string}
                             */
                            productRiskTier: "routine" | "elevated" | "high";
                            disclosureRuleIds?: string[];
                            bannedClaims?: string[];
                            /** @description Human-readable template logic for audit (BR-11). */
                            logicOutline?: string;
                            boundFactKeys?: string[];
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                            /** Format: date-time */
                            approvedAt?: string;
                            /** Format: date-time */
                            retiredAt?: string;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listDisclosureRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                disclosureRuleId: string;
                                name: string;
                                body: string;
                                bannedClaimPatterns?: string[];
                                /** @enum {string} */
                                status: "draft" | "approved" | "retired";
                            }[];
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createDisclosureRule: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    body: string;
                    bannedClaimPatterns?: string[];
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            disclosureRuleId: string;
                            name: string;
                            body: string;
                            bannedClaimPatterns?: string[];
                            /** @enum {string} */
                            status: "draft" | "approved" | "retired";
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
