/**
 * ExecuteMarkFactFieldAuthoritative - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: snapshots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteMarkFactFieldAuthoritative Use Case
 *
 * DDD: Application use case for get Authoritative.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { MarkFactFieldAuthoritativeInput, MarkFactFieldAuthoritativeOutput } from "../dto/authoritative.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { AuthoritativeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteMarkFactFieldAuthoritative {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly authoritative: AuthoritativeRepository
  ) {}

  async execute(input: MarkFactFieldAuthoritativeInput): Promise<MarkFactFieldAuthoritativeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.snpId();

    // All field names extracted from OpenAPI spec: authoritative
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).snapshotId) {
      throw new ValidationError("snapshotId is required");
    }
    const snapshotId = (input as any).snapshotId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.authoritative.markFactFieldAuthoritative({ snapshotId: snapshotId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${snapshotId}`);
    }

    return entity as MarkFactFieldAuthoritativeOutput;
  }
}
