/**
 * ExecuteCreateFactSnapshot - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: snapshots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateFactSnapshot Use Case
 *
 * DDD: Application use case for create Snapshot.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateFactSnapshotInput, CreateFactSnapshotOutput } from "../dto/snapshot.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { SnapshotRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateFactSnapshot {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly snapshot: SnapshotRepository
  ) {}

  async execute(input: CreateFactSnapshotInput): Promise<CreateFactSnapshotOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.snpId();

    // All field names extracted from OpenAPI spec: accountId, asOf, fields, periodKey
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.periodKey) {
      throw new ValidationError("periodKey is required");
    }
    if (!input.asOf) {
      throw new ValidationError("asOf is required");
    }
    if (!input.fields) {
      throw new ValidationError("fields is required");
    }
    if (!input.accountId) {
      throw new ValidationError("accountId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (snapshots domain)
    const entityId = this.idGenerator.snpId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.snapshot.createFactSnapshot({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateFactSnapshotOutput;
  }
}
