/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Narratives Domain Use Cases
 * 
 * List of all use case names for the narratives domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const NARRATIVES_USE_CASES = [
  "executeAddNarrativeJudgmentOverlay",
  "executeGenerateNarrative",
  "executeGetNarrative",
  "executeGetNarrativeProductivitySummary",
  "executeListNarratives"
] as const;
