/**
 * ListTemplate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListTemplatesParams } from "@narriva/core/templates";

export function createListTemplateRequest(overrides: Partial<ListTemplatesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
