/**
 * Template Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/templates.openapi.types.js";
import { schemas } from "../schemas/templates.schemas.js";

/**
 * Entity: TemplateEntity
 * Description: Represents the Template domain model.
 * Source: schemas.Template
 * Type: Domain Entity (API)
 */
export const TemplateEntitySchema = schemas.Template;
export type TemplateEntity = components["schemas"]["Template"];
