/**
 * DeliveryRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deliveries
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeliveryRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DeliveryRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DeliveryRepository,
} from "@narriva/services/deliveries";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DeliveryRepositoryDdb } from "./delivery-repository.ddb.js";

/**
 * DeliveryRepositoryAdapter
 *
 * Implements DeliveryRepository port for infrastructure layer.
 */
export class DeliveryRepositoryAdapter implements DeliveryRepository {
  private readonly ddb: DeliveryRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DeliveryRepositoryDdb(this.dynamoClient);
  }

  async listDeliveries(input: Parameters<DeliveryRepository['listDeliveries']>[0]): Promise<Awaited<ReturnType<DeliveryRepository['listDeliveries']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDeliveries(input);
  }

  async createDelivery(input: Parameters<DeliveryRepository['createDelivery']>[0]): Promise<Awaited<ReturnType<DeliveryRepository['createDelivery']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createDelivery(input);
  }

  async getDelivery(input: Parameters<DeliveryRepository['getDelivery']>[0]): Promise<Awaited<ReturnType<DeliveryRepository['getDelivery']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDelivery(input);
  }
}
