/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { productivityRoutes } from "./productivity.routes.js";
export { judgmentRoutes } from "./judgment.routes.js";
export { narrativeRoutes } from "./narrative.routes.js";
