/**
 * Routes for Judgment
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { addNarrativeJudgmentOverlay } from "../handlers/judgment.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function judgmentRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/narratives/{narrativeId}/judgment (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/narratives/:narrativeId/judgment",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { narrativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getNarrativesDependenciesForRequest();
        await addNarrativeJudgmentOverlay(request, reply, deps);
      });
    }
  );


}
