/**
 * Routes for Narrative
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { generateNarrative, getNarrative, listNarratives } from "../handlers/narrative.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function narrativeRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/narratives (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/narratives",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getNarrativesDependenciesForRequest();
        await generateNarrative(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/narratives (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/narratives",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getNarrativesDependenciesForRequest();
        await listNarratives(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/narratives/{narrativeId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/narratives/:narrativeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { narrativeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getNarrativesDependenciesForRequest();
        await getNarrative(request, reply, deps);
      });
    }
  );


}
