/**
 * Approval Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: approvals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/approvals.openapi.types.js";
import { schemas } from "../schemas/approvals.schemas.js";

/**
 * Entity: ApprovalEntity
 * Description: Represents the Approval domain model.
 * Source: schemas.Approval
 * Type: Domain Entity (API)
 */
export const ApprovalEntitySchema = schemas.Approval;
export type ApprovalEntity = components["schemas"]["Approval"];
