/**
 * ListSnapshot DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: snapshots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListFactSnapshotsParams } from "@narriva/core/snapshots";

export function createListSnapshotRequest(overrides: Partial<ListFactSnapshotsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
