/**
 * ApproveRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApproveRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ApproveRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ApproveRepository,
} from "@narriva/services/templates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ApproveRepositoryDdb } from "./approve-repository.ddb.js";

/**
 * ApproveRepositoryAdapter
 *
 * Implements ApproveRepository port for infrastructure layer.
 */
export class ApproveRepositoryAdapter implements ApproveRepository {
  private readonly ddb: ApproveRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ApproveRepositoryDdb(this.dynamoClient);
  }

  async approveTemplate(input: Parameters<ApproveRepository['approveTemplate']>[0]): Promise<Awaited<ReturnType<ApproveRepository['approveTemplate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.approveTemplate(input);
  }
}
