/**
 * DisclosureRuleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisclosureRuleRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DisclosureRuleRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DisclosureRuleRepository,
} from "@narriva/services/templates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DisclosureRuleRepositoryDdb } from "./disclosure-rule-repository.ddb.js";

/**
 * DisclosureRuleRepositoryAdapter
 *
 * Implements DisclosureRuleRepository port for infrastructure layer.
 */
export class DisclosureRuleRepositoryAdapter implements DisclosureRuleRepository {
  private readonly ddb: DisclosureRuleRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DisclosureRuleRepositoryDdb(this.dynamoClient);
  }

  async listDisclosureRules(input: Parameters<DisclosureRuleRepository['listDisclosureRules']>[0]): Promise<Awaited<ReturnType<DisclosureRuleRepository['listDisclosureRules']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDisclosureRules(input);
  }

  async createDisclosureRule(input: Parameters<DisclosureRuleRepository['createDisclosureRule']>[0]): Promise<Awaited<ReturnType<DisclosureRuleRepository['createDisclosureRule']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createDisclosureRule(input);
  }
}
