/**
 * RetireRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RetireRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RetireRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RetireRepository,
} from "@narriva/services/templates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RetireRepositoryDdb } from "./retire-repository.ddb.js";

/**
 * RetireRepositoryAdapter
 *
 * Implements RetireRepository port for infrastructure layer.
 */
export class RetireRepositoryAdapter implements RetireRepository {
  private readonly ddb: RetireRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RetireRepositoryDdb(this.dynamoClient);
  }

  async retireTemplate(input: Parameters<RetireRepository['retireTemplate']>[0]): Promise<Awaited<ReturnType<RetireRepository['retireTemplate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.retireTemplate(input);
  }
}
