/**
 * SubmitRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SubmitRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SubmitRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SubmitRepository,
} from "@narriva/services/templates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SubmitRepositoryDdb } from "./submit-repository.ddb.js";

/**
 * SubmitRepositoryAdapter
 *
 * Implements SubmitRepository port for infrastructure layer.
 */
export class SubmitRepositoryAdapter implements SubmitRepository {
  private readonly ddb: SubmitRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SubmitRepositoryDdb(this.dynamoClient);
  }

  async submitTemplateForApproval(input: Parameters<SubmitRepository['submitTemplateForApproval']>[0]): Promise<Awaited<ReturnType<SubmitRepository['submitTemplateForApproval']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitTemplateForApproval(input);
  }
}
