/**
 * RetireRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RetireRepository Port
 *
 * DDD: Application port for retirerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RetireTemplateInput, RetireTemplateOutput } from "../dto/retire.dto";
export interface RetireRepository {
  retireTemplate(input: RetireTemplateInput): Promise<RetireTemplateOutput>;
}

export type { RetireTemplateInput, RetireTemplateOutput } from "../dto/retire.dto";
