/**
 * TemplateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TemplateRepository Port
 *
 * DDD: Application port for templaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateTemplateInput, CreateTemplateOutput, GetTemplateInput, GetTemplateOutput, ListTemplatesInput, ListTemplatesOutput } from "../dto/template.dto";
export interface TemplateRepository {
  listTemplates(input: ListTemplatesInput): Promise<ListTemplatesOutput>;
  createTemplate(input: CreateTemplateInput): Promise<CreateTemplateOutput>;
  getTemplate(input: GetTemplateInput): Promise<GetTemplateOutput>;
}

export type { CreateTemplateInput, CreateTemplateOutput, GetTemplateInput, GetTemplateOutput, ListTemplatesInput, ListTemplatesOutput } from "../dto/template.dto";
