/**
 * LockRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: snapshots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LockRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LockRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LockRepository,
} from "@narriva/services/snapshots";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LockRepositoryDdb } from "./lock-repository.ddb.js";

/**
 * LockRepositoryAdapter
 *
 * Implements LockRepository port for infrastructure layer.
 */
export class LockRepositoryAdapter implements LockRepository {
  private readonly ddb: LockRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LockRepositoryDdb(this.dynamoClient);
  }

  async lockFactSnapshot(input: Parameters<LockRepository['lockFactSnapshot']>[0]): Promise<Awaited<ReturnType<LockRepository['lockFactSnapshot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.lockFactSnapshot(input);
  }
}
