/**
 * SnapshotRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: snapshots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SnapshotRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SnapshotRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SnapshotRepository,
} from "@narriva/services/snapshots";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SnapshotRepositoryDdb } from "./snapshot-repository.ddb.js";

/**
 * SnapshotRepositoryAdapter
 *
 * Implements SnapshotRepository port for infrastructure layer.
 */
export class SnapshotRepositoryAdapter implements SnapshotRepository {
  private readonly ddb: SnapshotRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SnapshotRepositoryDdb(this.dynamoClient);
  }

  async listFactSnapshots(input: Parameters<SnapshotRepository['listFactSnapshots']>[0]): Promise<Awaited<ReturnType<SnapshotRepository['listFactSnapshots']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFactSnapshots(input);
  }

  async createFactSnapshot(input: Parameters<SnapshotRepository['createFactSnapshot']>[0]): Promise<Awaited<ReturnType<SnapshotRepository['createFactSnapshot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createFactSnapshot(input);
  }

  async getFactSnapshot(input: Parameters<SnapshotRepository['getFactSnapshot']>[0]): Promise<Awaited<ReturnType<SnapshotRepository['getFactSnapshot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFactSnapshot(input);
  }
}
