/**
 * AuthoritativeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: snapshots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuthoritativeRepository Port
 *
 * DDD: Application port for authoritativerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { MarkFactFieldAuthoritativeInput, MarkFactFieldAuthoritativeOutput } from "../dto/authoritative.dto";
export interface AuthoritativeRepository {
  markFactFieldAuthoritative(input: MarkFactFieldAuthoritativeInput): Promise<MarkFactFieldAuthoritativeOutput>;
}

export type { MarkFactFieldAuthoritativeInput, MarkFactFieldAuthoritativeOutput } from "../dto/authoritative.dto";
