/**
 * Routes for Lock
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: snapshots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { lockFactSnapshot } from "../handlers/lock.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function lockRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/snapshots/{snapshotId}/lock (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/snapshots/:snapshotId/lock",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { snapshotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSnapshotsDependenciesForRequest();
        await lockFactSnapshot(request, reply, deps);
      });
    }
  );


}
