/**
 * DisclosureRule DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisclosureRule DTOs
 *
 * DDD: Application DTOs for DisclosureRule use cases.
 */

import type { CreateDisclosureRuleRequestInput } from "@narriva/core/templates/types";

export type ListDisclosureRulesInput = {};

export type CreateDisclosureRuleInput = CreateDisclosureRuleRequestInput;

export type ListDisclosureRulesOutput = {};

export type CreateDisclosureRuleOutput = {};
