/**
 * Retire DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Retire DTOs
 *
 * DDD: Application DTOs for Retire use cases.
 */

import type { RetireTemplateParams } from "@narriva/core/templates/types";

export type RetireTemplateInput = RetireTemplateParams;

export type RetireTemplateOutput = {};
