/**
 * Submit DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Submit DTOs
 *
 * DDD: Application DTOs for Submit use cases.
 */

import type { SubmitTemplateForApprovalParams } from "@narriva/core/templates/types";

export type SubmitTemplateForApprovalInput = SubmitTemplateForApprovalParams;

export type SubmitTemplateForApprovalOutput = {};
