/**
 * Template DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Template DTOs
 *
 * DDD: Application DTOs for Template use cases.
 */

import type { CreateTemplateRequestInput, GetTemplateParams, ListTemplatesParams } from "@narriva/core/templates/types";

export type ListTemplatesInput = ListTemplatesParams;

export type CreateTemplateInput = CreateTemplateRequestInput;

export type GetTemplateInput = GetTemplateParams;

export type ListTemplatesOutput = {};

export type CreateTemplateOutput = {};

export type GetTemplateOutput = {};
