/**
 * Narratives DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Narratives Domain Module - Composition root
 *
 * DDD: Composition root for narratives domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  JudgmentRepositoryAdapter,
  NarrativeRepositoryAdapter,
  ProductivityRepositoryAdapter,
} from "@narriva/adapters/narratives";
import { getIdGeneratorService } from "@narriva/adapters";
import type { AdapterDynamoDBClient } from "@narriva/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAddNarrativeJudgmentOverlay,
  ExecuteGenerateNarrative,
  ExecuteGetNarrative,
  ExecuteGetNarrativeProductivitySummary,
  ExecuteListNarratives,
} from "@narriva/services/narratives/usecases";
// Ports (interfaces)
import type {
  JudgmentRepository,
  NarrativeRepository,
  ProductivityRepository,
} from "@narriva/services/narratives/ports";

export interface NarrativesDomainModule {
  repos: {
    judgments: JudgmentRepository;
    narratives: NarrativeRepository;
    productivities: ProductivityRepository;
  };
  useCases: {
    judgments: {
      create: ExecuteAddNarrativeJudgmentOverlay;
    };
    narratives: {
      get: ExecuteGetNarrative;
      list: ExecuteListNarratives;
    };
    productivities: {
      get: ExecuteGetNarrativeProductivitySummary;
    };
  };
}

export function buildNarrativesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): NarrativesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      judgments?: JudgmentRepository;
      narratives?: NarrativeRepository;
      productivities?: ProductivityRepository;
    } = {};

    obj.judgments = new JudgmentRepositoryAdapter(dynamoClient);
    obj.narratives = new NarrativeRepositoryAdapter(dynamoClient);
    obj.productivities = new ProductivityRepositoryAdapter(dynamoClient);
    return {
      judgments: obj.judgments!,
      narratives: obj.narratives!,
      productivities: obj.productivities!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    judgments: {
      create: new ExecuteAddNarrativeJudgmentOverlay(executionContext, idGenerator, repos.judgments),
    },
    narratives: {
      get: new ExecuteGetNarrative(executionContext, idGenerator, repos.narratives),
      list: new ExecuteListNarratives(executionContext, idGenerator, repos.narratives),
    },
    productivities: {
      get: new ExecuteGetNarrativeProductivitySummary(executionContext, idGenerator, repos.productivities),
    },
  };
  return { repos, useCases: useCases as NarrativesDomainModule["useCases"] };
}
