/**
 * Reproduction DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reproductions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reproduction DTOs
 *
 * DDD: Application DTOs for Reproduction use cases.
 */

import type { CreateReproductionRequestInput, GetReproductionParams, ListReproductionsParams } from "@narriva/core/reproductions/types";

export type ListReproductionsInput = ListReproductionsParams;

export type CreateReproductionInput = CreateReproductionRequestInput;

export type GetReproductionInput = GetReproductionParams;

export type ListReproductionsOutput = {};

export type CreateReproductionOutput = {};

export type GetReproductionOutput = {};
