/**
 * UpdateCancel DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deliveries
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { CancelDeliveryParams } from "@narriva/core/deliveries";

export function createUpdateCancelRequest(overrides: Partial<CancelDeliveryParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
