/**
 * Snapshots DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: snapshots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Snapshots Domain Module - Composition root
 *
 * DDD: Composition root for snapshots domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AuthoritativeRepositoryAdapter,
  LockRepositoryAdapter,
  SnapshotRepositoryAdapter,
} from "@narriva/adapters/snapshots";
import { getIdGeneratorService } from "@narriva/adapters";
import type { AdapterDynamoDBClient } from "@narriva/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateFactSnapshot,
  ExecuteGetFactSnapshot,
  ExecuteListFactSnapshots,
  ExecuteLockFactSnapshot,
  ExecuteMarkFactFieldAuthoritative,
} from "@narriva/services/snapshots/usecases";
// Ports (interfaces)
import type {
  AuthoritativeRepository,
  LockRepository,
  SnapshotRepository,
} from "@narriva/services/snapshots/ports";

export interface SnapshotsDomainModule {
  repos: {
    authoritatives: AuthoritativeRepository;
    locks: LockRepository;
    snapshots: SnapshotRepository;
  };
  useCases: {
    authoritatives: {
      get: ExecuteMarkFactFieldAuthoritative;
    };
    locks: {
      get: ExecuteLockFactSnapshot;
    };
    snapshots: {
      create: ExecuteCreateFactSnapshot;
      get: ExecuteGetFactSnapshot;
      list: ExecuteListFactSnapshots;
    };
  };
}

export function buildSnapshotsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SnapshotsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      authoritatives?: AuthoritativeRepository;
      locks?: LockRepository;
      snapshots?: SnapshotRepository;
    } = {};

    obj.authoritatives = new AuthoritativeRepositoryAdapter(dynamoClient);
    obj.locks = new LockRepositoryAdapter(dynamoClient);
    obj.snapshots = new SnapshotRepositoryAdapter(dynamoClient);
    return {
      authoritatives: obj.authoritatives!,
      locks: obj.locks!,
      snapshots: obj.snapshots!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    authoritatives: {
      get: new ExecuteMarkFactFieldAuthoritative(executionContext, idGenerator, repos.authoritatives),
    },
    locks: {
      get: new ExecuteLockFactSnapshot(executionContext, idGenerator, repos.locks),
    },
    snapshots: {
      create: new ExecuteCreateFactSnapshot(executionContext, idGenerator, repos.snapshots),
      get: new ExecuteGetFactSnapshot(executionContext, idGenerator, repos.snapshots),
      list: new ExecuteListFactSnapshots(executionContext, idGenerator, repos.snapshots),
    },
  };
  return { repos, useCases: useCases as SnapshotsDomainModule["useCases"] };
}
