/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: reproductions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@narriva/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@narriva/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@narriva/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _approvals from "./approvals/index.js";
import * as _deliveries from "./deliveries/index.js";
import * as _identity from "./identity/index.js";
import * as _narratives from "./narratives/index.js";
import * as _reproductions from "./reproductions/index.js";
import * as _snapshots from "./snapshots/index.js";
import * as _templates from "./templates/index.js";

// Export as namespaces
export const approvals = _approvals;
export const deliveries = _deliveries;
export const identity = _identity;
export const narratives = _narratives;
export const reproductions = _reproductions;
export const snapshots = _snapshots;
export const templates = _templates;
