/**
 * Repository interface for Approval
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: approvals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ApprovalEntity
} from "../models/approval.entity.js";
import type {
  ListApprovalsParams,
  Approval
} from "../types/index.js";
/**
 * ApprovalRepository Interface
 */
export interface ApprovalRepository extends CreateReadRepository<ApprovalEntity, Approval, string, ListApprovalsParams> {

}
