/**
 * Routes for Cancel
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deliveries
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { cancelDelivery } from "../handlers/cancel.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function cancelRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/deliveries/{deliveryId}/cancel (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/deliveries/:deliveryId/cancel",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { deliveryId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDeliveriesDependenciesForRequest();
        await cancelDelivery(request, reply, deps);
      });
    }
  );


}
