/**
 * DisclosureRule Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DisclosureRuleEntity } from "@narriva/core/templates/models/index.js";
import { templatesSchemas } from "@narriva/core/templates";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "tpl";

export function createDisclosureRule(overrides: Partial<DisclosureRuleEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    body: overrides.body ?? faker.lorem.paragraph(),
    disclosureRuleId: overrides.disclosureRuleId ?? `dcl_${ulid().toLowerCase()}`,
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "draft",
    ...overrides,
  };

  return templatesSchemas.DisclosureRule.parse(raw);
}

export function disclosureRuleBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDisclosureRule(overrides));
}
