/**
 * CreateDisclosureRule handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createDisclosureRule } from "@narriva/api-server/domains/templates/handlers";
import type { TemplatesDDDDependencies } from "@narriva/api-server/domains/templates";
import { createDisclosureRule as createDisclosureRuleEntity } from "@narriva/factories/templates";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@narriva/tests/shared";
import { TEMPLATES_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateDisclosureRule", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TemplatesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TemplatesDDDDependencies>(
      TEMPLATES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createDisclosureRuleEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateDisclosureRule, "execute").mockResolvedValue(useCaseResult);

    await createDisclosureRule(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateDisclosureRule.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
