/**
 * Repository interface for Template
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  TemplateEntity
} from "../models/template.entity.js";
import type {
  ListTemplatesParams,
  Template
} from "../types/index.js";
/**
 * TemplateRepository Interface
 */
export interface TemplateRepository extends CreateReadRepository<TemplateEntity, Template, string, ListTemplatesParams> {

}
