/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./approve/index.js";
export * from "./disclosure-rule/index.js";
export * from "./retire/index.js";
export * from "./submit/index.js";
export * from "./template/index.js";
