/**
 * Cancel DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deliveries
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Cancel DTOs
 *
 * DDD: Application DTOs for Cancel use cases.
 */

import type { CancelDeliveryParams } from "@narriva/core/deliveries/types";

export type CancelDeliveryInput = CancelDeliveryParams;

export type CancelDeliveryOutput = {};
