/**
 * Templates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Templates Domain Module - Composition root
 *
 * DDD: Composition root for templates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ApproveRepositoryAdapter,
  DisclosureRuleRepositoryAdapter,
  RetireRepositoryAdapter,
  SubmitRepositoryAdapter,
  TemplateRepositoryAdapter,
} from "@narriva/adapters/templates";
import { getIdGeneratorService } from "@narriva/adapters";
import type { AdapterDynamoDBClient } from "@narriva/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApproveTemplate,
  ExecuteCreateDisclosureRule,
  ExecuteCreateTemplate,
  ExecuteGetTemplate,
  ExecuteListDisclosureRules,
  ExecuteListTemplates,
  ExecuteRetireTemplate,
  ExecuteSubmitTemplateForApproval,
} from "@narriva/services/templates/usecases";
// Ports (interfaces)
import type {
  ApproveRepository,
  DisclosureRuleRepository,
  RetireRepository,
  SubmitRepository,
  TemplateRepository,
} from "@narriva/services/templates/ports";

export interface TemplatesDomainModule {
  repos: {
    approves: ApproveRepository;
    disclosureRules: DisclosureRuleRepository;
    retires: RetireRepository;
    submits: SubmitRepository;
    templates: TemplateRepository;
  };
  useCases: {
    approves: {
      create: ExecuteApproveTemplate;
    };
    disclosureRules: {
      create: ExecuteCreateDisclosureRule;
      list: ExecuteListDisclosureRules;
    };
    retires: {
      get: ExecuteRetireTemplate;
    };
    submits: {
      create: ExecuteSubmitTemplateForApproval;
    };
    templates: {
      create: ExecuteCreateTemplate;
      get: ExecuteGetTemplate;
      list: ExecuteListTemplates;
    };
  };
}

export function buildTemplatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TemplatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      approves?: ApproveRepository;
      disclosureRules?: DisclosureRuleRepository;
      retires?: RetireRepository;
      submits?: SubmitRepository;
      templates?: TemplateRepository;
    } = {};

    obj.approves = new ApproveRepositoryAdapter(dynamoClient);
    obj.disclosureRules = new DisclosureRuleRepositoryAdapter(dynamoClient);
    obj.retires = new RetireRepositoryAdapter(dynamoClient);
    obj.submits = new SubmitRepositoryAdapter(dynamoClient);
    obj.templates = new TemplateRepositoryAdapter(dynamoClient);
    return {
      approves: obj.approves!,
      disclosureRules: obj.disclosureRules!,
      retires: obj.retires!,
      submits: obj.submits!,
      templates: obj.templates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    approves: {
      create: new ExecuteApproveTemplate(executionContext, idGenerator, repos.approves),
    },
    disclosureRules: {
      create: new ExecuteCreateDisclosureRule(executionContext, idGenerator, repos.disclosureRules),
      list: new ExecuteListDisclosureRules(executionContext, idGenerator, repos.disclosureRules),
    },
    retires: {
      get: new ExecuteRetireTemplate(executionContext, idGenerator, repos.retires),
    },
    submits: {
      create: new ExecuteSubmitTemplateForApproval(executionContext, idGenerator, repos.submits),
    },
    templates: {
      create: new ExecuteCreateTemplate(executionContext, idGenerator, repos.templates),
      get: new ExecuteGetTemplate(executionContext, idGenerator, repos.templates),
      list: new ExecuteListTemplates(executionContext, idGenerator, repos.templates),
    },
  };
  return { repos, useCases: useCases as TemplatesDomainModule["useCases"] };
}
