/**
 * ApprovalRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: approvals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApprovalRepository Port
 *
 * DDD: Application port for approvalrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateNarrativeApprovalInput, CreateNarrativeApprovalOutput, GetApprovalInput, GetApprovalOutput, ListApprovalsInput, ListApprovalsOutput } from "../dto/approval.dto";
export interface ApprovalRepository {
  listApprovals(input: ListApprovalsInput): Promise<ListApprovalsOutput>;
  createNarrativeApproval(input: CreateNarrativeApprovalInput): Promise<CreateNarrativeApprovalOutput>;
  getApproval(input: GetApprovalInput): Promise<GetApprovalOutput>;
}

export type { CreateNarrativeApprovalInput, CreateNarrativeApprovalOutput, GetApprovalInput, GetApprovalOutput, ListApprovalsInput, ListApprovalsOutput } from "../dto/approval.dto";
