/**
 * CreateReproduction handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reproductions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createReproduction } from "@narriva/api-server/domains/reproductions/handlers";
import type { ReproductionsDDDDependencies } from "@narriva/api-server/domains/reproductions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@narriva/tests/shared";
import { REPRODUCTIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateReproduction", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ReproductionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ReproductionsDDDDependencies>(
      REPRODUCTIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateReproduction, "execute").mockResolvedValue(useCaseResult);

    await createReproduction(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateReproduction.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
