/**
 * ExecuteGetNarrative - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetNarrative Use Case
 *
 * DDD: Application use case for get Narrative.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetNarrativeInput, GetNarrativeOutput } from "../dto/narrative.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { NarrativeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetNarrative {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly narrative: NarrativeRepository
  ) {}

  async execute(input: GetNarrativeInput): Promise<GetNarrativeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.narId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).narrativeId) {
      throw new ValidationError("narrativeId is required");
    }
    const narrativeId = (input as any).narrativeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.narrative.getNarrative({ narrativeId: narrativeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${narrativeId}`);
    }

    return entity as GetNarrativeOutput;
  }
}
