/**
 * ExecuteListNarratives - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListNarratives Use Case
 *
 * DDD: Application use case for list Narrative.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListNarrativesInput, ListNarrativesOutput } from "../dto/narrative.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { NarrativeRepository } from "../ports";

export class ExecuteListNarratives {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly narrative: NarrativeRepository
  ) {}

  async execute(input: ListNarrativesInput): Promise<ListNarrativesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.narId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.narrative.listNarratives({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListNarrativesOutput;
  }
}
