/**
 * ExecuteAddNarrativeJudgmentOverlay - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAddNarrativeJudgmentOverlay Use Case
 *
 * DDD: Application use case for create Judgment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AddNarrativeJudgmentOverlayInput, AddNarrativeJudgmentOverlayOutput } from "../dto/judgment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { JudgmentRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteAddNarrativeJudgmentOverlay {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly judgment: JudgmentRepository
  ) {}

  async execute(input: AddNarrativeJudgmentOverlayInput): Promise<AddNarrativeJudgmentOverlayOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.narId();

    // All field names extracted from OpenAPI spec: judgmentOverlay
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.judgmentOverlay) {
      throw new ValidationError("judgmentOverlay is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (narratives domain)
    const entityId = this.idGenerator.narId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.judgment.addNarrativeJudgmentOverlay({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as AddNarrativeJudgmentOverlayOutput;
  }
}
