/**
 * ExecuteGetNarrativeProductivitySummary - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: narratives
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetNarrativeProductivitySummary Use Case
 *
 * DDD: Application use case for get Productivity.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetNarrativeProductivitySummaryInput, GetNarrativeProductivitySummaryOutput } from "../dto/productivity.dto";
import type { ExecutionContextService, IdGeneratorService } from "@narriva/services/_shared/index.js";
import type { ProductivityRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetNarrativeProductivitySummary {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly productivity: ProductivityRepository
  ) {}

  async execute(input: GetNarrativeProductivitySummaryInput): Promise<GetNarrativeProductivitySummaryOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.narId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.productivity.getNarrativeProductivitySummary({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetNarrativeProductivitySummaryOutput;
  }
}
