/**
 * CancelRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deliveries
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CancelRepository Port
 *
 * DDD: Application port for cancelrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CancelDeliveryInput, CancelDeliveryOutput } from "../dto/cancel.dto";
import type { GetDeliveryInput, GetDeliveryOutput } from "../dto/delivery.dto";
export interface CancelRepository {
  getDelivery(input: GetDeliveryInput): Promise<GetDeliveryOutput | null>;
  cancelDelivery(input: CancelDeliveryInput): Promise<CancelDeliveryOutput>;
}

export type { CancelDeliveryInput, CancelDeliveryOutput } from "../dto/cancel.dto";
export type { GetDeliveryInput, GetDeliveryOutput } from "../dto/delivery.dto";
