/**
 * Approval DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: approvals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Approval DTOs
 *
 * DDD: Application DTOs for Approval use cases.
 */

import type { CreateNarrativeApprovalParams, CreateNarrativeApprovalRequestInput, GetApprovalParams, ListApprovalsParams } from "@narriva/core/approvals/types";

export type ListApprovalsInput = ListApprovalsParams;

export type CreateNarrativeApprovalInput = CreateNarrativeApprovalParams & CreateNarrativeApprovalRequestInput;

export type GetApprovalInput = GetApprovalParams;

export type ListApprovalsOutput = {};

export type CreateNarrativeApprovalOutput = {};

export type GetApprovalOutput = {};
