/**
 * Handlers for Lock
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: snapshots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SnapshotsDomainModule } from "../dependencies/snapshots-ddd.dependencies.js";
import type { LockFactSnapshotInput } from "@narriva/services/snapshots";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v0/tenants/me/snapshots/{snapshotId}/lock
 * Operation: lockFactSnapshot
 */
export async function lockFactSnapshot(
  request: FastifyRequest<{ Params: { snapshotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SnapshotsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: LockFactSnapshotInput = {
    snapshotId: request.params.snapshotId,
  };
  const result = await deps.useCases.locks.get.execute(input);
  return reply.code(200).send(result);
}


