/**
 * Handlers for DisclosureRule
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TemplatesDomainModule } from "../dependencies/templates-ddd.dependencies.js";
import type { CreateDisclosureRuleInput, ListDisclosureRulesInput } from "@narriva/services/templates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/disclosure-rules
 * Operation: listDisclosureRules
 */
export async function listDisclosureRules(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: TemplatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDisclosureRulesInput = {};
  const result = await deps.useCases.disclosureRules.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/disclosure-rules
 * Operation: createDisclosureRule
 */
export async function createDisclosureRule(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: TemplatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateDisclosureRuleInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.disclosureRules.create.execute(input);
  return reply.code(201).send(result);
}


