/**
 * Handlers for Submit
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TemplatesDomainModule } from "../dependencies/templates-ddd.dependencies.js";
import type { SubmitTemplateForApprovalInput } from "@narriva/services/templates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v0/tenants/me/templates/{templateId}/submit
 * Operation: submitTemplateForApproval
 */
export async function submitTemplateForApproval(
  request: FastifyRequest<{ Params: { templateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TemplatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitTemplateForApprovalInput = {
    templateId: request.params.templateId,
  };
  const result = await deps.useCases.submits.create.execute(input);
  return reply.code(200).send(result);
}


