/**
 * Handlers for Template
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TemplatesDomainModule } from "../dependencies/templates-ddd.dependencies.js";
import type { CreateTemplateInput, GetTemplateInput, ListTemplatesInput } from "@narriva/services/templates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v0/tenants/me/templates
 * Operation: listTemplates
 */
export async function listTemplates(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], audience?: string | string[], status?: string | string[], locale?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: TemplatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListTemplatesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.templates.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v0/tenants/me/templates
 * Operation: createTemplate
 */
export async function createTemplate(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: TemplatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateTemplateInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.templates.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v0/tenants/me/templates/{templateId}
 * Operation: getTemplate
 */
export async function getTemplate(
  request: FastifyRequest<{ Params: { templateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TemplatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetTemplateInput = {
    templateId: request.params.templateId,
  };
  const result = await deps.useCases.templates.get.execute(input);
  return reply.code(200).send(result);
}


