/**
 * Reproductions DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reproductions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reproductions Domain Module - Composition root
 *
 * DDD: Composition root for reproductions domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ReproductionRepositoryAdapter,
} from "@narriva/adapters/reproductions";
import { getIdGeneratorService } from "@narriva/adapters";
import type { AdapterDynamoDBClient } from "@narriva/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateReproduction,
  ExecuteGetReproduction,
  ExecuteListReproductions,
} from "@narriva/services/reproductions/usecases";
// Ports (interfaces)
import type {
  ReproductionRepository,
} from "@narriva/services/reproductions/ports";

export interface ReproductionsDomainModule {
  repos: {
    reproductions: ReproductionRepository;
  };
  useCases: {
    reproductions: {
      create: ExecuteCreateReproduction;
      get: ExecuteGetReproduction;
      list: ExecuteListReproductions;
    };
  };
}

export function buildReproductionsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ReproductionsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      reproductions?: ReproductionRepository;
    } = {};

    obj.reproductions = new ReproductionRepositoryAdapter(dynamoClient);
    return {
      reproductions: obj.reproductions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    reproductions: {
      create: new ExecuteCreateReproduction(executionContext, idGenerator, repos.reproductions),
      get: new ExecuteGetReproduction(executionContext, idGenerator, repos.reproductions),
      list: new ExecuteListReproductions(executionContext, idGenerator, repos.reproductions),
    },
  };
  return { repos, useCases: useCases as ReproductionsDomainModule["useCases"] };
}
