/**
 * CreateNarrativeApproval handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: approvals
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createNarrativeApproval } from "@narriva/api-server/domains/approvals/handlers";
import type { ApprovalsDDDDependencies } from "@narriva/api-server/domains/approvals";
import { createApproval as createApprovalEntity } from "@narriva/factories/approvals";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@narriva/tests/shared";
import { APPROVALS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateNarrativeApproval", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ApprovalsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ApprovalsDDDDependencies>(
      APPROVALS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createApprovalEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateNarrativeApproval, "execute").mockResolvedValue(useCaseResult);

    await createNarrativeApproval(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateNarrativeApproval.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
