/**
 * Routes for DisclosureRule
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createDisclosureRule, listDisclosureRules } from "../handlers/disclosure-rule.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function disclosureRuleRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/disclosure-rules (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/disclosure-rules",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTemplatesDependenciesForRequest();
        await createDisclosureRule(request, reply, deps);
      });
    }
  );


  // GET /v0/tenants/me/disclosure-rules (unscoped; scope set for security middleware)
  fastify.get(
    "/v0/tenants/me/disclosure-rules",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTemplatesDependenciesForRequest();
        await listDisclosureRules(request, reply, deps);
      });
    }
  );


}
