/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { disclosureRuleRoutes } from "./disclosure-rule.routes.js";
export { approveRoutes } from "./approve.routes.js";
export { retireRoutes } from "./retire.routes.js";
export { submitRoutes } from "./submit.routes.js";
export { templateRoutes } from "./template.routes.js";
