/**
 * Routes for Submit
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: templates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { submitTemplateForApproval } from "../handlers/submit.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function submitRoutes(fastify: FastifyInstance) {
  // POST /v0/tenants/me/templates/{templateId}/submit (unscoped; scope set for security middleware)
  fastify.post(
    "/v0/tenants/me/templates/:templateId/submit",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { templateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTemplatesDependenciesForRequest();
        await submitTemplateForApproval(request, reply, deps);
      });
    }
  );


}
